'use strict';

//This list is automatic generated with a script by inspecting
//the available layouts in the gaia repo.
var LAYOUTS = new Map();

LAYOUTS.set('af', 'Afrikaans');
LAYOUTS.set('ar', 'العربية');
LAYOUTS.set('bg-BDS', 'Български (БДС)');
LAYOUTS.set('bg-Pho-Ban', 'Български (БАН)');
LAYOUTS.set('bg-Pho-Trad', 'Български (Фонетична)');
LAYOUTS.set('bn-Avro', 'বাংলা - অভ্র');
LAYOUTS.set('bn-Probhat', 'বাংলা - প্রভাত');
LAYOUTS.set('bs', 'Bosanski');
LAYOUTS.set('ca', 'Català');
LAYOUTS.set('cs-qwerty', 'Česká (QWERTY)');
LAYOUTS.set('cs', 'Česká');
LAYOUTS.set('cy', 'Cymraeg');
LAYOUTS.set('da', 'Dansk');
LAYOUTS.set('de-Neo', 'Deutsch - Neo');
LAYOUTS.set('de', 'Deutsch');
LAYOUTS.set('dz-BT', 'རྫོང་ཁ');
LAYOUTS.set('el', 'Ελληνικό');
LAYOUTS.set('emoji', 'Emoji');
LAYOUTS.set('en-Africa', 'English (Africa)');
LAYOUTS.set('en-Colemak', 'Colemak');
LAYOUTS.set('en-Dvorak', 'Dvorak');
LAYOUTS.set('en-GB', 'English (UK)');
LAYOUTS.set('en-Neo', 'English - Neo');
LAYOUTS.set('en', 'English');
LAYOUTS.set('eo', 'Esperanto');
LAYOUTS.set('es-Americas', 'Español (Latinoamérica)');
LAYOUTS.set('es', 'Español');
LAYOUTS.set('eu', 'Euskara');
LAYOUTS.set('fa', 'فارسی');
LAYOUTS.set('ff', 'Pulaar-Fulfulde');
LAYOUTS.set('fr-CA', 'Français (Canadien)');
LAYOUTS.set('fr-CH', 'Français (Suisse)');
LAYOUTS.set('fr-Dvorak-bepo', 'Bépo');
LAYOUTS.set('fr', 'Français');
LAYOUTS.set('fy', 'Frysk');
LAYOUTS.set('ga', 'Gaeilge');
LAYOUTS.set('gd', 'Gàidhlig');
LAYOUTS.set('gl', 'Galego');
LAYOUTS.set('gv', 'Gaelg');
LAYOUTS.set('he', 'עִבְרִית');
LAYOUTS.set('hi', 'हिन्दी');
LAYOUTS.set('hr', 'Hrvatski');
LAYOUTS.set('hu', 'Magyar');
LAYOUTS.set('ig', 'Asụsụ Igbo');
LAYOUTS.set('it', 'Italiano');
LAYOUTS.set('jp-kanji', 'Japanese - Kanji');
LAYOUTS.set('ko', '한국어');
LAYOUTS.set('lt', 'Lietuvių');
LAYOUTS.set('lv', 'Latviešu');
LAYOUTS.set('mk', 'Македонски');
LAYOUTS.set('my', 'မြန်မာ');
LAYOUTS.set('nb', 'Norsk');
LAYOUTS.set('nl', 'Nederlands');
LAYOUTS.set('pl', 'Polski');
LAYOUTS.set('pt-BR', 'Português (do Brasil)');
LAYOUTS.set('pt-PT', 'Português (Europeu)');
LAYOUTS.set('ro', 'Română');
LAYOUTS.set('ru', 'Pусский');
LAYOUTS.set('sk', 'Slovenčina');
LAYOUTS.set('sq', 'Shqip');
LAYOUTS.set('sr-Cyrl', 'Српски');
LAYOUTS.set('sr-Latn', 'Srpski');
LAYOUTS.set('sv', 'Svenska');
LAYOUTS.set('ta', 'தமிழ்');
LAYOUTS.set('te', 'తెలుగు');
LAYOUTS.set('th', 'ไทย');
LAYOUTS.set('tr-F', 'Türkçe F');
LAYOUTS.set('tr-Q', 'Türkçe Q');
LAYOUTS.set('uk', 'Українська');
LAYOUTS.set('vi-Qwerty', 'Tiếng Việt (QWERTY)');
LAYOUTS.set('vi-Telex', 'Tiếng Việt (Telex)');
LAYOUTS.set('vi-Typewriter', 'Tiếng Việt');
LAYOUTS.set('wo', 'Wolof');
LAYOUTS.set('zh-Hans-Handwriting', '手写简体');
LAYOUTS.set('zh-Hans-Pinyin', '拼音');
LAYOUTS.set('zh-Hant-Zhuyin', '注音');
